services:
  api:
    build:
      context: .
      dockerfile: infrastructure/dockerfiles/Dockerfile
    container_name: api
    expose:
      - '8080'
    networks:
      - appnet
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - appnet
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./infrastructure/dockerfiles/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infrastructure/certs:/etc/ssl/certs:ro
    depends_on:
      - api
    networks:
      - appnet
    env_file:
      - .env

networks:
  appnet:
    driver: bridge

volumes:
  redis-data:
